apiVersion: v1
kind: Secret
metadata:
  name: cqrssecrets
  namespace: default
data:
  AzureWebJobsStorage: {{.Values.AzureWebJobsStorage}}       
  FUNCTIONS_WORKER_RUNTIME: ZG90bmV0                
  EVENTHUB_CONNECTIONSTRING: {{.Values.EVENTHUB_CONNECTIONSTRING}}  
  COSMOSDB_CONNECTIONSTRING: {{.Values.COSMOSDB_CONNECTIONSTRING}}   
  REDISCACHE_CONNECTIONSTRING: {{.Values.REDISCACHE_CONNECTIONSTRING}}
  APPINSIGHTS_INSTRUMENTATIONKEY: {{.Values.APPINSIGHTS_INSTRUMENTATIONKEY}}