name: CQRS deploy to Azure (Single Region)
on:
  workflow_dispatch:
    inputs:
      tags:
        description: 'CQRS Deployment to a single Azure Region'

jobs:
  deploy:
    name: Deploy CQRS
    runs-on: ubuntu-latest
    env:
        ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
        ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
        ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
        tf_actions_working_dir: './Infrastructure/terraform'
    defaults:
      run:
        working-directory: ${{ env.tf_actions_working_dir }}
    steps:
    - name: "Checkout"
      uses: actions/checkout@master

    - name: "Terraform Setup"
      uses: hashicorp/setup-terraform@v1

    - name: "Terraform Init"
      id: init
      run: terraform init
      
    - name: "Terraform Plan"
      id: plan
      run: terraform plan -out="cqrs.plan" -var "custom_domain=${{ secrets.CUSTOM_DOMAIN }}" -var "api_server_authorized_ip_ranges=${{ secrets.IP_ADDRESS }}" -var-file=actions-singleregion.tfvars
      continue-on-error: false 

    - name: "Terraform Apply"
      id: apply
      run: terraform apply -auto-approve cqrs.plan
